package com.xinmei365.font.model;

import android.util.Pair;

import com.xinmei365.font.R;

import java.util.ArrayList;
import java.util.List;

public class StickerFactory {
    private static List<Pair<String, List<Pair<String, Integer>>>> sStickerss;
    public static List<Pair<String, List<Pair<String, Integer>>>> getStickerss() {
        if (sStickerss == null) {
            sStickerss = new ArrayList<>();
            List<Pair<String, Integer>> stickers = new ArrayList<>();
            String text = "吃火锅";
            stickers.add(new Pair<String, Integer>(text + "_1", R.drawable.sticker_1_1));
            stickers.add(new Pair<String, Integer>(text + "_2", R.drawable.sticker_1_2));
            stickers.add(new Pair<String, Integer>(text + "_3", R.drawable.sticker_1_3));
            stickers.add(new Pair<String, Integer>(text + "_4", R.drawable.sticker_1_4));
            stickers.add(new Pair<String, Integer>(text + "_5", R.drawable.sticker_1_5));
            stickers.add(new Pair<String, Integer>(text + "_6", R.drawable.sticker_1_6));
            stickers.add(new Pair<String, Integer>(text + "_7", R.drawable.sticker_1_7));
            stickers.add(new Pair<String, Integer>(text + "_8", R.drawable.sticker_1_8));
            stickers.add(new Pair<String, Integer>(text + "_9", R.drawable.sticker_1_9));
            stickers.add(new Pair<String, Integer>(text + "_10", R.drawable.sticker_1_10));
            stickers.add(new Pair<String, Integer>(text + "_11", R.drawable.sticker_1_11));
            stickers.add(new Pair<String, Integer>(text + "_12", R.drawable.sticker_1_12));
            stickers.add(new Pair<String, Integer>(text + "_13", R.drawable.sticker_1_13));
            stickers.add(new Pair<String, Integer>(text + "_14", R.drawable.sticker_1_14));
            stickers.add(new Pair<String, Integer>(text + "_15", R.drawable.sticker_1_15));
            stickers.add(new Pair<String, Integer>(text + "_16", R.drawable.sticker_1_16));
            stickers.add(new Pair<String, Integer>(text + "_17", R.drawable.sticker_1_17));
            stickers.add(new Pair<String, Integer>(text + "_18", R.drawable.sticker_1_18));
            stickers.add(new Pair<String, Integer>(text + "_19", R.drawable.sticker_1_19));
            stickers.add(new Pair<String, Integer>(text + "_20", R.drawable.sticker_1_20));
            sStickerss.add(new Pair<String, List<Pair<String, Integer>>>(text, stickers));
            text = "鹅小葵";
            stickers = new ArrayList<>();
            stickers.add(new Pair<String, Integer>(text + "_1", R.drawable.sticker_2_1));
            stickers.add(new Pair<String, Integer>(text + "_2", R.drawable.sticker_2_2));
            stickers.add(new Pair<String, Integer>(text + "_3", R.drawable.sticker_2_3));
            stickers.add(new Pair<String, Integer>(text + "_4", R.drawable.sticker_2_4));
            stickers.add(new Pair<String, Integer>(text + "_5", R.drawable.sticker_2_5));
            stickers.add(new Pair<String, Integer>(text + "_6", R.drawable.sticker_2_6));
            stickers.add(new Pair<String, Integer>(text + "_7", R.drawable.sticker_2_7));
            stickers.add(new Pair<String, Integer>(text + "_8", R.drawable.sticker_2_8));
            stickers.add(new Pair<String, Integer>(text + "_9", R.drawable.sticker_2_9));
            stickers.add(new Pair<String, Integer>(text + "_10", R.drawable.sticker_2_10));
            stickers.add(new Pair<String, Integer>(text + "_11", R.drawable.sticker_2_11));
            stickers.add(new Pair<String, Integer>(text + "_12", R.drawable.sticker_2_12));
            stickers.add(new Pair<String, Integer>(text + "_13", R.drawable.sticker_2_13));
            stickers.add(new Pair<String, Integer>(text + "_14", R.drawable.sticker_2_14));
            stickers.add(new Pair<String, Integer>(text + "_15", R.drawable.sticker_2_15));
            stickers.add(new Pair<String, Integer>(text + "_16", R.drawable.sticker_2_16));
            stickers.add(new Pair<String, Integer>(text + "_17", R.drawable.sticker_2_17));
            stickers.add(new Pair<String, Integer>(text + "_18", R.drawable.sticker_2_18));
            stickers.add(new Pair<String, Integer>(text + "_19", R.drawable.sticker_2_19));
            stickers.add(new Pair<String, Integer>(text + "_20", R.drawable.sticker_2_20));
            stickers.add(new Pair<String, Integer>(text + "_21", R.drawable.sticker_2_21));
            stickers.add(new Pair<String, Integer>(text + "_22", R.drawable.sticker_2_22));
            stickers.add(new Pair<String, Integer>(text + "_23", R.drawable.sticker_2_23));
            stickers.add(new Pair<String, Integer>(text + "_24", R.drawable.sticker_2_24));
            sStickerss.add(new Pair<String, List<Pair<String, Integer>>>(text, stickers));
            text = "果味OK棚";
            stickers = new ArrayList<>();
            stickers.add(new Pair<String, Integer>(text + "_1", R.drawable.sticker_3_1));
            stickers.add(new Pair<String, Integer>(text + "_2", R.drawable.sticker_3_2));
            stickers.add(new Pair<String, Integer>(text + "_3", R.drawable.sticker_3_3));
            stickers.add(new Pair<String, Integer>(text + "_4", R.drawable.sticker_3_4));
            stickers.add(new Pair<String, Integer>(text + "_5", R.drawable.sticker_3_5));
            stickers.add(new Pair<String, Integer>(text + "_6", R.drawable.sticker_3_6));
            stickers.add(new Pair<String, Integer>(text + "_7", R.drawable.sticker_3_7));
            stickers.add(new Pair<String, Integer>(text + "_8", R.drawable.sticker_3_8));
            stickers.add(new Pair<String, Integer>(text + "_9", R.drawable.sticker_3_9));
            stickers.add(new Pair<String, Integer>(text + "_10", R.drawable.sticker_3_10));
            stickers.add(new Pair<String, Integer>(text + "_11", R.drawable.sticker_3_11));
            stickers.add(new Pair<String, Integer>(text + "_12", R.drawable.sticker_3_12));
            stickers.add(new Pair<String, Integer>(text + "_13", R.drawable.sticker_3_13));
            stickers.add(new Pair<String, Integer>(text + "_14", R.drawable.sticker_3_14));
            stickers.add(new Pair<String, Integer>(text + "_15", R.drawable.sticker_3_15));
            stickers.add(new Pair<String, Integer>(text + "_16", R.drawable.sticker_3_16));
            stickers.add(new Pair<String, Integer>(text + "_17", R.drawable.sticker_3_17));
            stickers.add(new Pair<String, Integer>(text + "_18", R.drawable.sticker_3_18));
            stickers.add(new Pair<String, Integer>(text + "_19", R.drawable.sticker_3_19));
            stickers.add(new Pair<String, Integer>(text + "_20", R.drawable.sticker_3_20));
            sStickerss.add(new Pair<String, List<Pair<String, Integer>>>(text, stickers));
            text = "朋友圈打卡选手";
            stickers = new ArrayList<>();
            stickers.add(new Pair<String, Integer>(text + "_1", R.drawable.sticker_4_1));
            stickers.add(new Pair<String, Integer>(text + "_2", R.drawable.sticker_4_2));
            stickers.add(new Pair<String, Integer>(text + "_3", R.drawable.sticker_4_3));
            stickers.add(new Pair<String, Integer>(text + "_4", R.drawable.sticker_4_4));
            stickers.add(new Pair<String, Integer>(text + "_5", R.drawable.sticker_4_5));
            stickers.add(new Pair<String, Integer>(text + "_6", R.drawable.sticker_4_6));
            stickers.add(new Pair<String, Integer>(text + "_7", R.drawable.sticker_4_7));
            stickers.add(new Pair<String, Integer>(text + "_8", R.drawable.sticker_4_8));
            stickers.add(new Pair<String, Integer>(text + "_9", R.drawable.sticker_4_9));
            stickers.add(new Pair<String, Integer>(text + "_10", R.drawable.sticker_4_10));
            stickers.add(new Pair<String, Integer>(text + "_11", R.drawable.sticker_4_11));
            stickers.add(new Pair<String, Integer>(text + "_12", R.drawable.sticker_4_12));
            stickers.add(new Pair<String, Integer>(text + "_13", R.drawable.sticker_4_13));
            stickers.add(new Pair<String, Integer>(text + "_14", R.drawable.sticker_4_14));
            stickers.add(new Pair<String, Integer>(text + "_15", R.drawable.sticker_4_15));
            stickers.add(new Pair<String, Integer>(text + "_16", R.drawable.sticker_4_16));
            sStickerss.add(new Pair<String, List<Pair<String, Integer>>>(text, stickers));
            text = "情侣画帖";
            stickers = new ArrayList<>();
            stickers.add(new Pair<String, Integer>(text + "_1", R.drawable.sticker_5_1));
            stickers.add(new Pair<String, Integer>(text + "_2", R.drawable.sticker_5_2));
            stickers.add(new Pair<String, Integer>(text + "_3", R.drawable.sticker_5_3));
            stickers.add(new Pair<String, Integer>(text + "_4", R.drawable.sticker_5_4));
            stickers.add(new Pair<String, Integer>(text + "_5", R.drawable.sticker_5_5));
            stickers.add(new Pair<String, Integer>(text + "_6", R.drawable.sticker_5_6));
            stickers.add(new Pair<String, Integer>(text + "_7", R.drawable.sticker_5_7));
            stickers.add(new Pair<String, Integer>(text + "_8", R.drawable.sticker_5_8));
            stickers.add(new Pair<String, Integer>(text + "_9", R.drawable.sticker_5_9));
            stickers.add(new Pair<String, Integer>(text + "_10", R.drawable.sticker_5_10));
            stickers.add(new Pair<String, Integer>(text + "_11", R.drawable.sticker_5_11));
            stickers.add(new Pair<String, Integer>(text + "_12", R.drawable.sticker_5_12));
            stickers.add(new Pair<String, Integer>(text + "_13", R.drawable.sticker_5_13));
            stickers.add(new Pair<String, Integer>(text + "_14", R.drawable.sticker_5_14));
            stickers.add(new Pair<String, Integer>(text + "_15", R.drawable.sticker_5_15));
            stickers.add(new Pair<String, Integer>(text + "_16", R.drawable.sticker_5_16));
            stickers.add(new Pair<String, Integer>(text + "_17", R.drawable.sticker_5_17));
            stickers.add(new Pair<String, Integer>(text + "_18", R.drawable.sticker_5_18));
            stickers.add(new Pair<String, Integer>(text + "_19", R.drawable.sticker_5_19));
            stickers.add(new Pair<String, Integer>(text + "_20", R.drawable.sticker_5_20));
            stickers.add(new Pair<String, Integer>(text + "_21", R.drawable.sticker_5_21));
            stickers.add(new Pair<String, Integer>(text + "_22", R.drawable.sticker_5_22));
            stickers.add(new Pair<String, Integer>(text + "_23", R.drawable.sticker_5_23));
            stickers.add(new Pair<String, Integer>(text + "_24", R.drawable.sticker_5_24));
            sStickerss.add(new Pair<String, List<Pair<String, Integer>>>(text, stickers));
        }
        return sStickerss;
    }
}
